FROM registry.redhat.io/ubi9/nodejs-22:latest AS builder

USER root

RUN dnf install -y nginx npm

WORKDIR /src/yarn

COPY yarn-v1-install .
    
# Install yarn
RUN npm install --offline && \
    ln -s $PWD/node_modules/yarn/bin/yarn /usr/local/bin/yarn && \
    \
    # Show node and yarn versions
    echo "Currently running: " node --version && \
    echo "Currently running: " yarn --version

RUN yarn config set network-concurrency 1 && \
    yarn config set network-timeout 100000

RUN mkdir -p /var/cache/nginx /var/log/nginx /run && \
    chmod -R 777 /var/cache/nginx /var/log/nginx /run /usr/share/nginx/html/

WORKDIR /usr/src/app

# Copy license
COPY console-plugin-0.1.5/LICENSE /licenses/LICENSE
# Copy over the package.json/lock file only 
COPY console-plugin-0.1.5/package.json console-plugin-0.1.5/yarn.lock ./

# Cleaning up dependencies
RUN yarn clean
RUN rm -rf ./node_modules

# Tell yarn to fetch dependencies from /cachi2/output/deps/yarn-classic/
RUN yarn install --offline

# Copy the rest of the contents from upstream repo to container
COPY console-plugin-0.1.5/ .

# Run downstream replacements script & production build
RUN yarn downstream-replacements
RUN yarn build

RUN pwd && ls -la
RUN ls -la ./dist

RUN cp -r ./dist/* /usr/share/nginx/html/

RUN cp entrypoint.sh /usr/share/nginx/html/

RUN test -f /usr/share/nginx/html/plugin-manifest.json && \
    test -f /usr/share/nginx/html/entrypoint.sh && \
    test -d /usr/share/nginx/html/locales && \
    echo "All required files are present."

FROM registry.redhat.io/ubi9/nginx-126:latest AS runner

COPY --from=builder /usr/share/nginx/html/ /usr/share/nginx/html/
COPY --from=builder licenses/LICENSE /licenses/LICENSE

LABEL version="0.1.5" \
      com.redhat.component="rhcl-console-plugin-container" \
      name="rhcl-1/rhcl-console-plugin-rhel9" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      description="Console Plugin for Red Hat Connectivity Link" \
      io.k8s.display-name="Red Hat Connectivity Link Console Plugin" \
      io.openshift.tags="api" \
      io.k8s.description="" \
      maintainer="jmadigan@redhat.com" 

USER 1001
ENTRYPOINT ["/usr/share/nginx/html/entrypoint.sh"]
